server:
  port: ${SERVER_PORT:8080}
spring:
  security:
    user:
      name: admin
      password: 123
      role: ADMIN
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/to_do_list
    username: postgres
    password: postgres
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
